### ISSUE TITLE
Add task completion method / date

### ISSUE THREAD

**Issue by jakelowen** [gpsimpact/census-relational-organizing-frontend#135] opened 2020-01-21 16:21 UTC
Can we add a "contact method" dropdown at the bottom of each task, to indicate whether that particular task was done in-person, over the phone, etc., and a "date completed" calendar function? This ideally would also automatically add a "canvassed" contact attempt to the contact history for that particular day.

**Comment by jrazmi** [comment] 2020-01-23 17:00
Closing - duplicate of #110

**Closed by jrazmi** 2020-01-23 17:00 UTC
